version: "3.9"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  analyzer:
    build: .
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: postgres
      DB_USER: postgres
      DB_PASSWORD: postgres
      OPENROUTER_API_KEY: ${OPENROUTER_API_KEY}
    command: >
      sh -c "
      python sqlParse.py ./example.sql &&
      python explainRunner.py &&
      python LLM_aggregator.py --results explain_results.json --report llm_report.json &&
      python report_converter.py llm_report.json /app/report.html
      "
    volumes:
      - .:/app

  jenkins:
    image: jenkins/jenkins:lts
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - .:/app